CREATE DATABASE IF NOT EXISTS galorDB;
USE galorDB;

CREATE TABLE IF NOT EXISTS user(
	idUser INT PRIMARY KEY AUTO_INCREMENT,
    nombreUser VARCHAR(100) NOT NULL,
    ap1 VARCHAR(100) NOT NULL,
    ap2 VARCHAR(100),
    nickname VARCHAR(25) NOT NULL,
    passwd VARCHAR(25) NOT NULL,
    correoUser VARCHAR(200) NOT NULL,
    fotoPerfil LONGBLOB
);